version: "3.1"

services:
  server:
    build:
      context: ./server/
    ports:
      - "8080:5000"
    expose:
      - "5000"
    volumes:
      - ./server:/app

  front:
    build:
      context: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true


