version: "3"

services:
  server:
    build:
      context: ./server/
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./server/:/server/
    command:
      ["catalina.sh", "run"]

