version: "3.1"

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testapp
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"

  server:
    build:
      context: ./server/
    ports:
      - "8081:8080"
    volumes:
      - ./server:/app
    environment:
      - CLASSPATH:/app/sample.war

  front:
    build:
      context: ./front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true
    command: yarn serve --port 8000


