version: "3.1"

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testapp
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"

  server:
    build:
      context: ./server/
    ports:
      - "8081:5000"
    expose:
      - "5000"
    volumes:
      - ./server:/app

  front:
    build:
      context: ./front
    ports:
      - "8082:8082"
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true


